version: '3'

tasks:
  enable:
    desc: Install secrets slice
    cmds:
      - bash {{.TASKFILE_DIR}}/external-secrets/install.sh

  disable:
    desc: Uninstall secrets slice
    cmds:
      - helm uninstall -n external-secrets external-secrets || true
      - kubectl delete ns external-secrets --ignore-not-found
